- name: list files
  gather_facts: no
  hosts: dev_simple
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - command: find /home/user
      name: Shell Command
      register: cmd_out
    - debug:
        msg: "{{ cmd_out.stdout_lines }}"
