# declare hosts
proj:
  children:
    dev:
      hosts:
        dev_simple:
        dev_other:

# assign hosts to groups
    simple:
      hosts:
        dev_simple:
    other:
      hosts:
        dev_other:
