---
- include_vars: vars/main.yml

- include_tasks: root_tasks.yml
  vars:
    become_user: root
  tags:
    - root_tasks
  when: can_become_root | default(true)

- include_tasks: download_resources_locally.yml

- include_tasks: non_root_tasks.yml
