- name: start local-test
  gather_facts: no
  hosts: localhost
  tasks:
    - shell: whoami && hostname && ls -la
      name: Shell Command
      register: cmd_out
      delegate_to: localhost
    - debug:
        msg: "{{ cmd_out.stdout_lines }}"
