name: Lint master Branch after push
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work
      # linting
#      - name: setup Ansible
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r .github/workflows/python_requirements.txt; fi
      - name: run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2
