name: Test master Branch after push
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # linting
#      - name: run ansible-lint
#        uses: ansible-community/ansible-lint-action@v6.0.2
#        with:
#          args: "playbooks" # my ansible files in a folder
      # setup
#      - name: setup Ansible
#        run: |
#          python -m pip install --upgrade pip
#          if [ -f requirements.txt ]; then pip install -r .github/workflows/python_requirements.txt; fi

      - name: tomcat_java_test
        run: |
          .test/docker/clean_centos/up.sh
          .github/workflows/change_ansible_port.sh
          docker exec centos_base_container /usr/bin/nmap -PT22 localhost
          docker exec centos_base_container /bin/bash -c "export ANSIBLE_CONFIG=ansible.cfg; cd /repo; ./.test/tomcat_java_test/run_playbooks.sh"
          sleep 2 && curl localhost:8080

