name: Test master Branch after push
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # linting
#      - name: run ansible-lint
#        uses: ansible-community/ansible-lint-action@v6.0.2
#        with:
#          args: "playbooks" # my ansible files in a folder
      # setup
      - name: setup Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r .github/workflows/python_requirements.txt; fi

      - name: up.sh
        run: bash .test/docker/clean_centos/up.sh

      - uses: "MTES-MCT/nmap-action@main"
        with:
          host: localhost
          outputDir: 'scans'
          outputFile: 'nmapvuln.json'
          raw: false

      - name: testing
        run: cat scans/nmapvuln.json

      # run test
      - name: run simple_test
        run: bash .test/simple_test/test.sh
      - name: run tomcat_java_test
        run: bash .test/tomcat_java_test/test.sh
