name: Test master Branch after push
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # linting
      - name: setup Ansible
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r .github/workflows/python_requirements.txt; fi
      - name: run ansible-lint
        uses: ansible-community/ansible-lint-action@v6.0.2

      - name: test
        run: |
          .test/simple_test/test.sh
          .test/tomcat_java_test/test.sh
